{
  "escolas": {
    "Ensino_Fundamental": [
      "CARNEIRO RIBEIRO",
      "CENTRO EDUCACIONAL DO TRABALHADOR",
      "COLEGIO LUZIA SILVA",
      "DELMINDA FARIAS DE ALMEIDA",
      "EMANOEL DE OLIVEIRA BRITO",
      "EVERALDO SOUZA SANTOS",
      "JOAQUIM NERY DE SOUZA",
      "LOURIVAL ROSA DE SENA",
      "MENANDRO MINAHIM",
      "MONTEIRO LOBATO",
      "MUNICIPAL DIANA JUSSIENE",
      "NÚCLEO",
      "PRESIDENTE CASTELO BRANCO",
      "RURAL DE IPIUNA",
      "STELA CAMARA DUBOIS",
      "TERRABRAS",
      "VICENZO GASBARRE"
    ],
    "Educação_Infantil": [
      "ARLINDA EMILIA DE ASSIS",
      "ALEGRIA DE VIVER",
      "CENTRO SOCIAL URBANO - CRECHE",
      "CRECHE M. MARLEIDE PINTO DE N. NUNES",
      "ERALDO TINOCO DE MELO",
      "GRUPO ESCOLAR LOMANTO JUNIOR",
      "MONTEIRO LOBATO",
      "MUNICIPAL IRMA DULCE",
      "NÚCLEO",
      "PRESIDENTE CASTELO BRANCO",
      "RURAL DE IPIUNA",
      "STELA CAMARA DUBOIS",
      "TERRABRAS"
    ]
  }
}
